// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6qYHdGB3pmRYlYBuTxxWVFaowIGLNDss',
    appId: '1:376402680768:web:d64de26cbb4a08e6238625',
    messagingSenderId: '376402680768',
    projectId: 'tourism-398213',
    authDomain: 'tourism-398213.firebaseapp.com',
    storageBucket: 'tourism-398213.appspot.com',
    measurementId: 'G-E628Y43KDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIvHBegXkxPlJVKy-O_-D_rPbGIrzlUR4',
    appId: '1:376402680768:android:c4e0916f70714d5e238625',
    messagingSenderId: '376402680768',
    projectId: 'tourism-398213',
    storageBucket: 'tourism-398213.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCReCc8mQykC03a8OoL0einbWhXqfZyc7o',
    appId: '1:376402680768:ios:20648c2687ac4c96238625',
    messagingSenderId: '376402680768',
    projectId: 'tourism-398213',
    storageBucket: 'tourism-398213.appspot.com',
    iosClientId: '376402680768-7a11vq05o99m4mhkmnnrcgfj0piu6fl3.apps.googleusercontent.com',
    iosBundleId: 'com.example.funAdventure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCReCc8mQykC03a8OoL0einbWhXqfZyc7o',
    appId: '1:376402680768:ios:4c5916a76cc6b96f238625',
    messagingSenderId: '376402680768',
    projectId: 'tourism-398213',
    storageBucket: 'tourism-398213.appspot.com',
    iosClientId: '376402680768-d0did5dkeilgqmgovq9hs7u560i0a0og.apps.googleusercontent.com',
    iosBundleId: 'com.example.funAdventure.RunnerTests',
  );
}
